
package com.youssef.service.orders;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-26T08:59:17.654+02:00
 * Generated source version: 3.1.7
 * 
 */
public final class Orders_OrdersSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.youssef.com/service/Orders/", "Orders");

    private Orders_OrdersSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Orders_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Orders_Service ss = new Orders_Service(wsdlURL, SERVICE_NAME);
        Orders port = ss.getOrdersSOAP();  
        
        {
        System.out.println("Invoking processOrderPlacement...");
        com.youssef.schema.order.OrderInquiryType _processOrderPlacement_orderInquiry = null;
        com.youssef.schema.order.OrderInquiryResponseType _processOrderPlacement__return = port.processOrderPlacement(_processOrderPlacement_orderInquiry);
        System.out.println("processOrderPlacement.result=" + _processOrderPlacement__return);


        }

        System.exit(0);
    }

}
